name: Source Code Vulnerability Scan

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Source Code Vulnerability Scan
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            semgrep/semgrep \
            semgrep scan --config auto /src
